# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PflipUav3
                                 A QGIS plugin
 Photogrammetric and Remote Sensing Flight Planning for unmanned aerial vehicle
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-08-23
        git sha              : $Format:%H$
        copyright            : (C) 2019 by David Hernández López, PAFYC-UCLM
        email                : david.hernandez@uclm.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# import PyQt5 classes

# import PyQGIS classes


# import self classes

# imports other classes

# others imports
import os

# import self classes
from .. import config as c  # constants

class Python3GenericMethods():
    """
    Frecuent Python3 operations
    """
    def __init__(self,
                 iface):
        """
        Constructor class method
        :param iface: user interface QGIS
        :type iface: QgsInterface
        """
        self.iface = iface